changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Exciting New Features 🎉
      labels:
        - feature
    - title: Bug fixes 🔥
      labels:
        - bugfix
    - title: Hot fixes 🐛🔥
      labels:
        - hotfix
    - title: Dependencies 👒
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
